import type { PersonalAssessmentQuestion } from './personal-assessment.schema';
import {
  BUDGET_RESPONSIBILITY,
  FEEDBACK_PREFERENCE,
  INDUSTRIES,
  INTERNATIONAL_ORG_EXPERIENCE,
  INTERNATIONAL_STAKEHOLDERS,
  LARGEST_ORG_SIZE,
  LED_PROJECT_UNSUPERVISED,
  LEADERSHIP_TITLES,
  MANAGED_TEAM,
  MENTORING_EXPERIENCE,
  ORG_TYPES,
  PRIMARY_LANGUAGE,
  PRIMARY_TOOL_DURATION,
  REMOTE_EXPERIENCE,
  REMOTE_WORKSPACE_SETUP,
  SHIPPED_DELIVERABLE,
  STUDENT_STATUS,
  TIME_ZONES_COLLABORATED,
  WORK_ARRANGEMENT_PREFERENCE,
  YEARS_EXPERIENCE,
  YES_NO,
} from './personal-assessment.schema';

type TestQuestionSeed = PersonalAssessmentQuestion & { sectionSlug: string };

const SECTION_SLUGS = [
  'professional_background',
  'skills_and_expertise',
  'leadership_and_responsibility',
  'international_and_remote_experience',
  'work_style',
] as const;

function q(
  sectionIndex: number,
  question: Omit<PersonalAssessmentQuestion, 'track'> & { track?: string },
): TestQuestionSeed {
  return {
    track: 'all',
    ...question,
    sectionSlug: SECTION_SLUGS[sectionIndex],
  };
}

/** In-memory catalog used by unit/e2e tests (not loaded from DB). */
export const PERSONAL_ASSESSMENT_TEST_QUESTIONS: TestQuestionSeed[] = [
  q(0, {
    externalId: 'PA-TEST-001',
    key: 'job_title',
    questionNumber: 1,
    inputType: 'text_required',
    required: true,
    minLength: 2,
    maxLength: 150,
    prompt: 'Job Title',
  }),
  q(0, {
    externalId: 'PA-TEST-002',
    key: 'years_experience',
    questionNumber: 2,
    inputType: 'single',
    required: true,
    options: YEARS_EXPERIENCE,
    prompt: 'Years Experience',
  }),
  q(0, {
    externalId: 'PA-TEST-003',
    key: 'industries',
    questionNumber: 3,
    inputType: 'multi',
    required: true,
    options: INDUSTRIES,
    otherTextKey: 'industries_other',
    prompt: 'Industries',
  }),
  q(0, {
    externalId: 'PA-TEST-004',
    key: 'largest_org_size',
    questionNumber: 4,
    inputType: 'single',
    required: true,
    options: LARGEST_ORG_SIZE,
    prompt: 'Largest Org Size',
  }),
  q(0, {
    externalId: 'PA-TEST-005',
    key: 'org_types',
    questionNumber: 5,
    inputType: 'multi',
    required: true,
    options: ORG_TYPES,
    prompt: 'Org Types',
  }),
  q(0, {
    externalId: 'PA-TEST-006',
    key: 'education_level',
    questionNumber: 6,
    inputType: 'single',
    required: true,
    skipStorage: true,
    profileField: 'education_level',
    prompt: 'Education Level',
  }),
  q(0, {
    externalId: 'PA-TEST-007',
    key: 'student_status',
    questionNumber: 7,
    inputType: 'single',
    required: true,
    options: STUDENT_STATUS,
    prompt: 'Student Status',
  }),
  q(0, {
    externalId: 'PA-TEST-008',
    key: 'country',
    questionNumber: 8,
    inputType: 'text_required',
    required: true,
    minLength: 2,
    maxLength: 100,
    skipStorage: true,
    profileField: 'country',
    prompt: 'Country',
  }),
  q(0, {
    externalId: 'PA-TEST-009',
    key: 'region',
    questionNumber: 9,
    inputType: 'text_required',
    required: true,
    minLength: 2,
    maxLength: 100,
    skipStorage: true,
    profileField: 'region',
    prompt: 'Region',
  }),
  q(0, {
    externalId: 'PA-TEST-010',
    key: 'primary_language',
    questionNumber: 10,
    inputType: 'single',
    required: true,
    options: PRIMARY_LANGUAGE,
    otherTextKey: 'primary_language_other',
    prompt: 'Primary Language',
  }),
  q(1, {
    externalId: 'PA-TEST-011',
    key: 'skill_track',
    questionNumber: 11,
    inputType: 'single',
    required: true,
    skipStorage: true,
    profileField: 'track',
    prompt: 'Skill Track',
  }),
  q(1, {
    externalId: 'PA-TEST-012',
    key: 'specialization',
    questionNumber: 12,
    inputType: 'single',
    required: true,
    prompt: 'Specialization',
  }),
  q(1, {
    externalId: 'PA-TEST-013',
    key: 'claimed_level',
    questionNumber: 13,
    inputType: 'single',
    required: true,
    prompt: 'Claimed Level',
  }),
  q(1, {
    externalId: 'PA-TEST-014',
    key: 'tools',
    questionNumber: 14,
    inputType: 'multi',
    required: false,
    otherTextKey: 'tools_other',
    prompt: 'Tools',
  }),
  q(1, {
    externalId: 'PA-TEST-015',
    key: 'primary_tool_duration',
    questionNumber: 15,
    inputType: 'single',
    required: true,
    options: PRIMARY_TOOL_DURATION,
    prompt: 'Primary Tool Duration',
  }),
  q(1, {
    externalId: 'PA-TEST-016',
    key: 'mentoring_experience',
    questionNumber: 16,
    inputType: 'single',
    required: true,
    options: MENTORING_EXPERIENCE,
    prompt: 'Mentoring Experience',
  }),
  q(1, {
    externalId: 'PA-TEST-017',
    key: 'shipped_deliverable',
    questionNumber: 17,
    inputType: 'single',
    required: true,
    options: SHIPPED_DELIVERABLE,
    prompt: 'Shipped Deliverable',
  }),
  q(1, {
    externalId: 'PA-TEST-018',
    key: 'portfolio_url',
    questionNumber: 18,
    inputType: 'text_optional',
    required: false,
    maxLength: 500,
    skipStorage: true,
    profileField: 'linkedin_url',
    prompt: 'Portfolio Url',
  }),
  q(2, {
    externalId: 'PA-TEST-019',
    key: 'managed_team',
    questionNumber: 19,
    inputType: 'single',
    required: true,
    options: MANAGED_TEAM,
    prompt: 'Managed Team',
  }),
  q(2, {
    externalId: 'PA-TEST-020',
    key: 'leadership_titles',
    questionNumber: 20,
    inputType: 'multi',
    required: true,
    options: LEADERSHIP_TITLES,
    prompt: 'Leadership Titles',
  }),
  q(2, {
    externalId: 'PA-TEST-021',
    key: 'difficult_decision_narrative',
    questionNumber: 21,
    inputType: 'text_required',
    required: true,
    minLength: 80,
    maxLength: 1000,
    prompt: 'Difficult Decision Narrative',
  }),
  q(2, {
    externalId: 'PA-TEST-022',
    key: 'led_project_unsupervised',
    questionNumber: 22,
    inputType: 'single',
    required: true,
    options: LED_PROJECT_UNSUPERVISED,
    prompt: 'Led Project Unsupervised',
  }),
  q(2, {
    externalId: 'PA-TEST-023',
    key: 'hiring_experience',
    questionNumber: 23,
    inputType: 'single',
    required: true,
    options: YES_NO,
    prompt: 'Hiring Experience',
  }),
  q(2, {
    externalId: 'PA-TEST-024',
    key: 'budget_responsibility',
    questionNumber: 24,
    inputType: 'single',
    required: true,
    options: BUDGET_RESPONSIBILITY,
    prompt: 'Budget Responsibility',
  }),
  q(3, {
    externalId: 'PA-TEST-025',
    key: 'international_org_experience',
    questionNumber: 25,
    inputType: 'single',
    required: true,
    options: INTERNATIONAL_ORG_EXPERIENCE,
    prompt: 'International Org Experience',
  }),
  q(3, {
    externalId: 'PA-TEST-026',
    key: 'remote_experience',
    questionNumber: 26,
    inputType: 'single',
    required: true,
    options: REMOTE_EXPERIENCE,
    prompt: 'Remote Experience',
  }),
  q(3, {
    externalId: 'PA-TEST-027',
    key: 'time_zones_collaborated',
    questionNumber: 27,
    inputType: 'single',
    required: true,
    options: TIME_ZONES_COLLABORATED,
    prompt: 'Time Zones Collaborated',
  }),
  q(3, {
    externalId: 'PA-TEST-028',
    key: 'international_stakeholders',
    questionNumber: 28,
    inputType: 'single',
    required: true,
    options: INTERNATIONAL_STAKEHOLDERS,
    prompt: 'International Stakeholders',
  }),
  q(3, {
    externalId: 'PA-TEST-029',
    key: 'work_arrangement_preference',
    questionNumber: 29,
    inputType: 'multi',
    required: true,
    options: WORK_ARRANGEMENT_PREFERENCE,
    prompt: 'Work Arrangement Preference',
  }),
  q(3, {
    externalId: 'PA-TEST-030',
    key: 'remote_workspace_setup',
    questionNumber: 30,
    inputType: 'single',
    required: true,
    options: REMOTE_WORKSPACE_SETUP,
    prompt: 'Remote Workspace Setup',
  }),
  q(4, {
    externalId: 'PA-TEST-031',
    key: 'deadline_handling',
    questionNumber: 31,
    inputType: 'text_required',
    required: true,
    minLength: 60,
    maxLength: 1000,
    prompt: 'Deadline Handling',
  }),
  q(4, {
    externalId: 'PA-TEST-032',
    key: 'ideal_work_environment',
    questionNumber: 32,
    inputType: 'text_required',
    required: true,
    minLength: 60,
    maxLength: 1000,
    prompt: 'Ideal Work Environment',
  }),
  q(4, {
    externalId: 'PA-TEST-033',
    key: 'feedback_preference',
    questionNumber: 33,
    inputType: 'single',
    required: true,
    options: FEEDBACK_PREFERENCE,
    prompt: 'Feedback Preference',
  }),
  q(4, {
    externalId: 'PA-TEST-034',
    key: 'professional_disagreement',
    questionNumber: 34,
    inputType: 'text_optional',
    required: false,
    minLength: 60,
    maxLength: 1000,
    prompt: 'Professional Disagreement',
  }),
  q(4, {
    externalId: 'PA-TEST-035',
    key: 'workload_management',
    questionNumber: 35,
    inputType: 'text_required',
    required: true,
    minLength: 60,
    maxLength: 1000,
    prompt: 'Workload Management',
  }),
  q(4, {
    externalId: 'PA-TEST-036',
    key: 'quick_learning_narrative',
    questionNumber: 36,
    inputType: 'text_required',
    required: true,
    minLength: 60,
    maxLength: 1000,
    prompt: 'Quick Learning Narrative',
  }),
];

export function getOnboardingBackedQuestionKeysFromTestQuestions(): readonly string[] {
  return PERSONAL_ASSESSMENT_TEST_QUESTIONS.filter(
    (question) => question.skipStorage,
  ).map((question) => question.key);
}
